version: "3"

services:
  minecraftserver:
    image: itzg/minecraft-server:stable
    container_name: minecraft-server
    volumes:
      - ./data:/data
      - ./minecraft-server-mods.txt:/data/minecraft-server-mods.txt
      - ./.env:/data/.env.txt
      - ./mods:/data/mods
    ports:
      - 25565:25565
    environment:
      VERSION: "1.21.0"
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      NEOFORGE_VERSION: "beta"
      ONLINE_MODE: "true"
      MEMORY: "3G"
      INIT_MEMORY: "3G"
      MAX_MEMORY: "3G"
      SEED: 13790671
      MOTD: "Recordad portaros bien muchachos"
      MAX_PLAYERS: 5
      DIFFICULTY: "normal"
      OPS: "bunno6661"
      EXISTING_OPS_FILE: "SYNCHRONIZE"
      ICON: "https://i.pinimg.com/originals/7b/4f/5f/7b4f5fb2785f755a831f3697517abe41.png"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      VIEW_DISTANCE: 6
      MODE: "survival"
      SERVER_NAME: "Niños con cancer"
      ALLOW_FLIGHT: "TRUE"
      #MODS_FILE: "/data/minecraft-server-mods.txt"
      CF_API_KEY: "${CF_API_KEY}"
    tty: true
    stdin_open: true
    restart: unless-stopped
