version: "3.8"

services:
  minecraftserver:
    image: itzg/minecraft-server:stable
    container_name: minecraft-server
    hostname: minecraft-server
    volumes:
      - ./data:/data
      - ./.env:/data/.env
      - ./mods:/data/mods
    ports:
      - 25565:25565
    environment:
      VERSION: ${VERSION}
      EULA: ${EULA}
      TYPE: ${TYPE}
      NEOFORGE_VERSION: ${NEOFORGE_VERSION}
      ONLINE_MODE: ${ONLINE_MODE}
      MEMORY: ${MEMORY}
      INIT_MEMORY: ${INIT_MEMORY}
      MAX_MEMORY: ${MAX_MEMORY}
      #SEED: ${SEED}
      MOTD: ${MOTD}
      MAX_PLAYERS: ${MAX_PLAYERS}
      DIFFICULTY: ${DIFFICULTY}
      OPS: ${OPS}
      EXISTING_OPS_FILE: ${EXISTING_OPS_FILE}
      ICON: ${ICON}
      ALLOW_NETHER: ${ALLOW_NETHER}
      ANNOUNCE_PLAYER_ACHIEVEMENTS: ${ANNOUNCE_PLAYER_ACHIEVEMENTS}
      GENERATE_STRUCTURES: ${GENERATE_STRUCTURES}
      HARDCORE: ${HARDCORE}
      SNOOPER_ENABLED: ${SNOOPER_ENABLED}
      SPAWN_ANIMALS: ${SPAWN_ANIMALS}
      SPAWN_MONSTERS: ${SPAWN_MONSTERS}
      SPAWN_NPCS: ${SPAWN_NPCS}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      MODE: ${MODE}
      SERVER_NAME: ${SERVER_NAME}
      ALLOW_FLIGHT: ${ALLOW_FLIGHT}
    tty: true
    stdin_open: true
    restart: unless-stopped
