version: "3"

services:
  minecraftserver:
    image: itzg/minecraft-server
    container_name: minecraft-server
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      ONLINE_MODE: "true"
      Memory: "2G"
      SEED: 34488218
      MOTD: "Recordad portaros bien muchachos"
      DIFFICULTY: "normal"
      OPS: "bunno6661"
      EXISTING_OPS_FILE: "SYNCHRONIZE"
      ICON: "https://i.pinimg.com/originals/7b/4f/5f/7b4f5fb2785f755a831f3697517abe41.png"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      SNOOPER_ENABLED: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      VIEW_DISTANCE: 10
      MODE: "survival"
      SERVER_NAME: "Niños con cancer"
    tty: true
    stdin_open: true
    restart: unless-stopped
