apiVersion: v1
kind: Secret
metadata:
  name: nfs-credentials
  namespace: minecraft-server
type: Opaque
data:
  # Los valores deben estar codificados en base64
  username: <BASE64_USERNAME>
  password: <BASE64_PASSWORD>
# Para codificar tus credenciales en base64, puedes usar un comando como este:
# echo -n 'tu_username' | base64
# echo -n 'tu_password' | base64
